AirlineReservations/Controllers/AirlinesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AirlineReservations.Areas.Identity.Data;
using AirlineReservations.Models;
using Microsoft.AspNetCore.Authorization;

namespace AirlineReservations.Controllers
{
    [Authorize(Roles ="Admin")]
    public class AirlinesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AirlinesController(ApplicationDbContext context)
        {
            _context = context;
        }

       
        public async Task<IActionResult> Index()
        {
              return View(await _context.airlines.ToListAsync());
        }

      
        public IActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Airlinecode,AirlineName")] Airline airline)
        {
            if (ModelState.IsValid)
            {
                _context.Add(airline);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(airline);
        }

      
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.airlines == null)
            {
                return NotFound();
            }

            var airline = await _context.airlines.FindAsync(id);
            if (airline == null)
            {
                return NotFound();
            }
            return View(airline);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Airlinecode,AirlineName")] Airline airline)
        {
            if (id != airline.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(airline);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AirlineExists(airline.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(airline);
        }

       
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.airlines == null)
            {
                return NotFound();
            }

            var airline = await _context.airlines
                .FirstOrDefaultAsync(m => m.Id == id);
            if (airline == null)
            {
                return NotFound();
            }

            return View(airline);
        }

      
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.airlines == null)
            {
                return Problem("Entity set 'ApplicationDbContext.airlines'  is null.");
            }
            var airline = await _context.airlines.FindAsync(id);
            if (airline != null)
            {
                _context.airlines.Remove(airline);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AirlineExists(int id)
        {
          return _context.airlines.Any(e => e.Id == id);
        }
    }
}

AirlineReservations/Controllers/PassengerController.cs
using AirlineReservations.Areas.Identity.Data;
using AirlineReservations.Models;
using AirlineReservations.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Operations;

namespace AirlineReservations.Controllers
{

    [Authorize(Roles ="Customer")]
    public class PassengerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public PassengerController(ApplicationDbContext context,UserManager<ApplicationUser> userManager)
        {
            _context=context;
            _userManager=userManager;
        }
        public IActionResult Airline()
        {
            var ShowAirline = _context.airlines.ToList();
            return View(ShowAirline);
        }

        public IActionResult CityAirlineRoute(int id)
        {
            var GetRouteDetils = _context.routes.Where(x => x.AirlineId == id).ToList();
            
            return View(GetRouteDetils);
        }
        
       
        public IActionResult BookingTicket(int?id,int Rid)
        {
            TempData["ID"] =  Rid;

            var MatchAirline= (from ticket in _context.Tickets 
                               where ticket.AirlineID == id select new TicketViewModel
                               {
                                   TicketFrom=ticket.TicketFrom,
                                   TicketTo=ticket.TicletTo,
                                   TimeFrom=ticket.TimeFrom,
                                   TimeTo=ticket.TimeTo,
                                   TotalTicket=ticket.TotalSeata,
                                   SingleWayPrice=ticket.SinglePrice,
                                   TwoWayPrice=ticket.TwoWaysPrice,
                                   TicketId=ticket.Id,
                                   airlineName=ticket.Airline.AirlineName,
                                   AirlineCode=ticket.Airline.Airlinecode,
                                   PassangerClass=ticket.bookingClass.ClassTpye
                                }).ToList();
            return View(MatchAirline);
        }

        public IActionResult ConfirmTicket(int id)
        {
            var getTicketInfo = (from ticket in _context.Tickets
                            join city in _context.routes on ticket.AirlineID equals city.AirlineId
                            where ticket.Id == id
                            select new ConfirmViewModel
                            {
                                TicketFrom=ticket.TicketFrom,
                                TicketTo=ticket.TicletTo,
                                singlePrice=ticket.SinglePrice,
                                TwoWayPrice=ticket.TwoWaysPrice,
                                TimeFrom=ticket.TimeFrom,
                                TimeTo=ticket.TimeTo,
                                PassangerClass=ticket.bookingClass.ClassTpye,
                                ticketid=ticket.Id,
                                RouteFromCity=city.RouteFromCity,
                                RoutetoCity=city.RouteToCity

                            }).FirstOrDefault();
            return View(getTicketInfo);
        }

        [HttpPost]
        public async Task<IActionResult> UserConfirmTicket(int Price, int Seat,int id, string PhoneNumber,string Name,string Adress, string City)
        {
           
            BookingDetails booking = new BookingDetails();

           

            string userId = _userManager.GetUserId(User);

            var getdata = _context.Tickets.Where(x => x.Id == id).FirstOrDefault();

            bool check = _context.Tickets.Select(x=>x.SinglePrice==Price).FirstOrDefault();

            if (check == true)
            {
                booking.From = getdata.TicketFrom;
                booking.To = getdata.TicletTo;
                booking.ReturnTime = getdata.TimeTo;
                booking.DepartureTime = getdata.TimeFrom;
                booking.TicketsId = id;
                booking.Seats = Seat;
                booking.TicketStatus = "Pending";
                booking.userId = userId;
                booking.TicketPrice = Price;
               
                booking.RouteId = Convert.ToInt32(TempData["ID"]);

                _context.Add(booking);
               
               int SaveCheck=  _context.SaveChanges();

                if(SaveCheck==1)
                {
                    TempData["ID"] = null;
                }
                    var user =  await _userManager.FindByIdAsync(userId);
                    await _userManager.SetPhoneNumberAsync(user, PhoneNumber);
                    user.Adress = Adress;
                    user.City = City;
                    user.Name = Name;
                    await _userManager.UpdateAsync(user);
                    var getTicketSeats = _context.Tickets.Find(id);

                    getTicketSeats.TotalSeata = getTicketSeats.TotalSeata - Seat;
                    
                    _context.Update(getTicketSeats);
                    _context.SaveChanges();

                    return RedirectToAction("TicketConfirmation");
            }
           
            else
            {
                booking.From = getdata.TicketFrom;
                booking.To = getdata.TicletTo;
                booking.ReturnTime = getdata.TimeTo;
                booking.DepartureTime = getdata.TimeFrom;
                booking.TicketsId = id;
                booking.Seats = Seat;
                booking.TicketStatus = "Pending";
                booking.userId = userId;
                booking.TicketPrice = Price;
                booking.RouteId = Convert.ToInt32(TempData["ID"]);
                _context.Add(booking);
               int SavedCheck=  _context.SaveChanges();
                if(SavedCheck==1)
                {
                    TempData["ID"] = null;
                }
                var user = await _userManager.FindByIdAsync(userId);
                
                    await _userManager.SetPhoneNumberAsync(user, PhoneNumber);
                    user.Adress = Adress;
                    user.City = City;
                    user.Name = Name;
                    await _userManager.UpdateAsync(user);
                    var getTicketSeats = _context.Tickets.Find(id);
                    getTicketSeats.TotalSeata = getTicketSeats.TotalSeata - Seat;
                    _context.Update(getTicketSeats);
                    _context.SaveChanges();

                    return RedirectToAction("TicketConfirmation");
            }

           
        }

        public IActionResult TicketConfirmation()
        {
            return View();
        }

        public IActionResult UserHistory()
        {
            string userId = _userManager.GetUserId(User);


            var getOrder = (from user in _context.Users
                            join bokingDetail in _context.bookingDetails on user.Id equals bokingDetail.userId
                            join tick in _context.Tickets on bokingDetail.TicketsId equals tick.Id
                            join airline in _context.airlines on tick.AirlineID equals airline.Id
                            where bokingDetail.userId == userId
                            select new PassangerViewModel
                            {
                                PassengerName=user.Name,
                                AirlineName=airline.AirlineName,
                                TicketFrom=tick.TicketFrom,
                                TicketPrice=bokingDetail.TicketPrice,
                                TicketTimeTo=bokingDetail.ReturnTime,
                                TicketTo=tick.TicletTo,
                                AirlineClassType=tick.bookingClass.ClassTpye,
                                BookingDetialsId = bokingDetail.BookingID,
                                Status = bokingDetail.TicketStatus
                            }).ToList();


           
            return View(getOrder);
        }

        public IActionResult CancelOrder(int id)
        {
            var getOrderDetails=_context.bookingDetails.Find(id);
            if (getOrderDetails == null)
            {
                return NotFound();
            }
            else
            {
                getOrderDetails.TicketStatus = "Cancel";
                _context.bookingDetails.Update(getOrderDetails);
                _context.SaveChanges();
                return RedirectToAction("UserHistory");
            }

           
        }
    }
}

AirlineReservations/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AirlineReservations.Areas.Identity.Data;
using AirlineReservations.Models;
using Microsoft.AspNetCore.Authorization;

namespace AirlineReservations.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TicketsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TicketsController(ApplicationDbContext context)
        {
            _context = context;
        }

       
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Tickets.Include(t => t.Airline).Include(t => t.bookingClass);
            return View(await applicationDbContext.ToListAsync());
        }

      
        public IActionResult Create()
        {
            ViewData["AirlineID"] = new SelectList(_context.airlines, "Id", "AirlineName");
            ViewData["ClassTypeID"] = new SelectList(_context.bookingClass, "Id", "ClassTpye");
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TicketFrom,TicletTo,TimeFrom,TimeTo,TotalSeata,SinglePrice,TwoWaysPrice,AirlineID,ClassTypeID")] Tickets tickets)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tickets);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AirlineID"] = new SelectList(_context.airlines, "Id", "AirlineName", tickets.AirlineID);
            ViewData["ClassTypeID"] = new SelectList(_context.bookingClass, "Id", "ClassTpye", tickets.ClassTypeID);
            return View(tickets);
        }

       
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Tickets == null)
            {
                return NotFound();
            }

            var tickets = await _context.Tickets.FindAsync(id);
            if (tickets == null)
            {
                return NotFound();
            }
            ViewData["AirlineID"] = new SelectList(_context.airlines, "Id", "AirlineName", tickets.AirlineID);
            ViewData["ClassTypeID"] = new SelectList(_context.bookingClass, "Id", "ClassTpye", tickets.ClassTypeID);
            return View(tickets);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TicketFrom,TicletTo,TimeFrom,TimeTo,TotalSeata,SinglePrice,TwoWaysPrice,AirlineID,ClassTypeID")] Tickets tickets)
        {
            if (id != tickets.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tickets);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TicketsExists(tickets.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AirlineID"] = new SelectList(_context.airlines, "Id", "AirlineName", tickets.AirlineID);
            ViewData["ClassTypeID"] = new SelectList(_context.bookingClass, "Id", "ClassTpye", tickets.ClassTypeID);
            return View(tickets);
        }

       
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Tickets == null)
            {
                return NotFound();
            }

            var tickets = await _context.Tickets
                .Include(t => t.Airline)
                .Include(t => t.bookingClass)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tickets == null)
            {
                return NotFound();
            }

            return View(tickets);
        }

      
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Tickets == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Tickets'  is null.");
            }
            var tickets = await _context.Tickets.FindAsync(id);
            if (tickets != null)
            {
                _context.Tickets.Remove(tickets);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TicketsExists(int id)
        {
          return _context.Tickets.Any(e => e.Id == id);
        }
    }
}

AirlineReservations/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using AirlineReservations.Areas.Identity.Data

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
        @ViewData["Title"] Rezervarea companiei aeriene
    </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AirlineReservations.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Airline Reservation</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (!User.IsInRole("Admin"))
                        {

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Acasă</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Passenger" asp-action="Airline">Companie aeriană</a>
                        </li>
                        }
                        @if (User.IsInRole("Customer"))
                        {

                            @if (SignInManager.IsSignedIn(User))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Passenger" asp-action="UserHistory">Istoric comenzi</a>
                                </li>
                            }

                        }
                        else if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Airlines" asp-action="Index">Adăugați o companie aeriană</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="BookingClasses" asp-action="Index">Tipul clasei</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CityRoutes" asp-action="Index">Traseul orașului</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="Index">Adăugați bilete</a>
                            </li>

                            <li class="dropdown">
                                <a class="nav-link text-dark dropdown-toggle" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">Detaliile comenzii utilizatorului</a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="AllOrder">Lista tuturor comenzilor</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="CancelOrder">Anulează lista comenzilor</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="ConfirmOrder">Confirmați lista comenzilor</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="PendingOrder">Lista comenzilor în așteptare</a>
                                    </li>
                                    
                                </ul>
                            </li>

                        }

                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>

    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Rezervarea companiei aeriene
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>